### ISSUE TITLE
siwifi_error_ind(0) (type 0, restart : 0, dump_en : 1): dump received

### ISSUE THREAD

**Issue by fengmushu** [Siflower/1806_SDK#15]
[   20.065735] kmodloader: loading kernel modules from /etc/modules.d/*
[   20.086095] ntfs: driver 2.1.32 [Flags: R/O MODULE].
[   20.100775] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   20.114317] ip_set: protocol 6
[   20.156314] siwifi_send_msg: bypassing (SIWIFI_DEV_RESTARTING set) 0x00
[   20.159293] u32 classifier
[   20.162985] set max idx to LMAC failed!
[   20.165689]     input device check on
[   20.169599] [1]Stop colling fail,ret -1
[   20.173254]     Actions configured
[   20.177246] siwifi_send_msg: bypassing (SIWIFI_DEV_RESTARTING set) 0x00
[   20.183240] Mirror/redirect action on
[   20.187235] set max idx to LMAC failed!
[   20.194766] [1]Stop colling fail,ret -1
[   20.200296] fuse init (API version 7.26)
[   20.210281] ctnetlink v0.93: registering with nfnetlink.
[   20.230491] PPP generic driver version 2.4.2
[   20.236594] NET: Registered protocol family 24
[   20.244745] kmodloader: done loading kernel modules from /etc/modules.d/*
[   23.983669] set port:1 pvid:1
[   23.986786] set port:2 pvid:1
[   23.989795] set port:3 pvid:1
[   23.993590] add port:1 for vlan:1 tagged:0
[   23.998308] add port:2 for vlan:1 tagged:0
[   24.002941] add port:3 for vlan:1 tagged:0
[   24.007622] add port:5 for vlan:1 tagged:1
[   24.011983] set port:0 pvid:2
[   24.015782] add port:0 for vlan:2 tagged:0
[   24.020500] add port:5 for vlan:2 tagged:1
[   24.024773] set port:5 pvid:2
[   26.815759] eswitch init success
[   26.827161] gmac open success
[   26.839732] br-lan: port 1(eth0.1) entered blocking state
[   26.845248] br-lan: port 1(eth0.1) entered disabled state
[   26.851651] device eth0.1 entered promiscuous mode
[   26.856879] device eth0 entered promiscuous mode
[   26.867666] br-lan: port 1(eth0.1) entered blocking state
[   26.873165] br-lan: port 1(eth0.1) entered forwarding state
[   26.879830] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   27.646386] hb-fmac 17800000.wifi-hb wlan1: Remove Interface
[   27.652214] found hnat device to del
[   27.806569] lb-fmac 11000000.wifi-lb wlan0: Remove Interface
[   27.812338] found hnat device to del
[   27.879877] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   29.614314] found hnat device to add
[   29.618234] [hnat notice]add wifi dev index 7 ndev8644c000
[   29.697575] found hnat device to add
[   29.701256] [hnat notice]add wifi dev index 6 ndev8644b000
[   30.236453] siwifi_send_msg: bypassing (SIWIFI_DEV_RESTARTING set) 0x00
[   30.243187] set max idx to LMAC failed!
[   30.247469] [1]Stop colling fail,ret -1
[   31.448266] lmac[0] vif_mgmt_register, vif_type : 2 status=0 index=0
[   31.454746] lmac[0] use normal txpower table
[   31.460528] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   31.478228] lmac[1] vif_mgmt_register, vif_type : 2 status=0 index=0
[   31.484629] lmac[1] use normal txpower table
[   31.490849] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
[   31.497236] br-lan: port 2(wlan0) entered blocking state
[   31.502591] br-lan: port 2(wlan0) entered disabled state
[   31.508960] device wlan0 entered promiscuous mode
[   31.516313] br-lan: port 3(wlan1) entered blocking state
[   31.521745] br-lan: port 3(wlan1) entered disabled state
[   31.528065] device wlan1 entered promiscuous mode
[   31.533439] br-lan: port 3(wlan1) entered blocking state
[   31.538968] br-lan: port 3(wlan1) entered forwarding state
[   32.477566] br-lan: port 3(wlan1) entered disabled state
[   39.538174] hb-fmac 17800000.wifi-hb wlan1: AP started: ch=0, bcmc_idx=64
[   39.545084] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[   39.552221] br-lan: port 3(wlan1) entered blocking state
[   39.557706] br-lan: port 3(wlan1) entered forwarding state
[   40.388201] lb-fmac 11000000.wifi-lb wlan0: AP started: ch=0, bcmc_idx=64
[   40.395288] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   40.402246] br-lan: port 2(wlan0) entered blocking state
[   40.407736] br-lan: port 2(wlan0) entered forwarding state
[   92.383088] lmac[1] rc_init: station_id=0 format_mod=4 pre_type=0 short_gi=1 max_bw=2
[   92.391066] lmac[1] rc_init: nss_max=1 mcs_max=9 r_idx_min=12 r_idx_max=12 no_samples=10
[   92.399694] hb-fmac 17800000.wifi-hb wlan1: Add sta 0 (a8:7e:ea:ec:f1:80) flags=[SHORT_PREAMBLE][WME][AUTHENTICATED][ASSOCIATED]
[  161.199063] lmac[0] rc_init: station_id=0 format_mod=2 pre_type=0 short_gi=1 max_bw=0
[  161.207014] lmac[0] rc_init: nss_max=1 mcs_max=7 r_idx_min=0 r_idx_max=3 no_samples=10
[  161.215284] lb-fmac 11000000.wifi-lb wlan0: Add sta 0 (e8:4e:06:40:70:5c) flags=[SHORT_PREAMBLE][WME][AUTHENTICATED][ASSOCIATED]
[  229.416798] siwifi_error_ind(0) (type 0, restart : 0, dump_en : 1): dump received
[  393.166284] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  393.179446] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  394.586679] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  394.603105] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  395.920173] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  395.932954] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  400.914970] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  400.929377] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  401.761271] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  401.772430] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  432.165241] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  432.179328] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  434.825741] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  434.841499] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  435.056593] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  435.072086] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  435.179362] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  435.193170] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  435.466288] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  435.481562] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  439.247674] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  439.257624] siwifi_hw->dbgdump_elem.err_cur_idx 0,0,866c0380,0,10
[  439.272638] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  441.032455] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  441.047856] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  441.513604] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  441.529279] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  444.393998] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  444.406469] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  448.510267] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  448.525664] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  449.406591] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  449.420505] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  450.596050] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  450.610137] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  451.213496] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  451.229034] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  454.284341] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  454.297970] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  454.661108] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763
[  454.676417] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  457.070996] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763

**Comment by fengmushu** [comment]
[  476.059356] siwifi_hw->dbgdump_elem.err_cur_idx 2,2,866c0900,0,10
[  476.070215] siwifi_error_ind(1) (type 0, restart : 0, dump_en : 1): dump received
[  477.881987] lmac[1] ASSERT (!(genirq_pending & NXMAC_PT_ERROR_BIT)) at macsw/ip/lmac/src/hal/hal_machw.c:763



BusyBox v1.29.3 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 SiWiFi openwrt1806_release_a28_ac28_sf19a28_fullmask_rel_, LEDE
 -----------------------------------------------------
root@OpenWrt:/# [  490.076034] wait cmd timeout, tout : 6000(ms), defer_push : 0!
[  490.081909] tkn[151]  flags:001a  result: -4  cmd:  63-MM_BCN_CHANGE_REQ        - reqcfm(  64-MM_BCN_CHANGE_CFM)
[  490.092180] tkn[151]  flags:001a  result: -4  cmd:  63-MM_BCN_CHANGE_REQ        - reqcfm(  64-MM_BCN_CHANGE_CFM)
[  490.102597] [hb]gic mask : 0x2000000, pending : 0x8000002
[  490.108076] ipc_env->reg_base : b7800000
[  490.112016] a2e status : 0x2, raw staus : 0x32, mask : 0x1f03, trigger(e2a) : 0x0
[  490.119700] [by API]e2a status : 0x0, raw staus : 0x0, mask : 0x0, trigger(a2e) : 0x0
[  490.127725] siwifi_hw->dbgdump_elem.err_cur_idx 3,3,866c0e80,54,2
[  496.141075] cmd queue[1] crashed
[  496.144351] siwifi_hw->dbgdump_elem.err_cur_idx 4,4,867d4100,-20,1
[  501.916383] cmd queue[1] crashed
[  501.919658] set max idx to LMAC failed!
[  501.923497] [1]Stop colling fail,ret -1
[  502.152544] cmd queue[1] crashed
[  508.157369] cmd queue[1] crashed
[  509.916089] cmd queue[1] crashed
[  510.236381] cmd queue[1] crashed
[  510.239652] set max idx to LMAC failed!
[  510.243486] [1]Stop colling fail,ret -1
[  512.316310] cmd queue[1] crashed
[  512.319585] set max idx to LMAC failed!
[  512.323426] [1]Stop colling fail,ret -1
[  514.164441] cmd queue[1] crashed
[  516.476260] cmd queue[1] crashed
[  516.479532] set max idx to LMAC failed!
[  516.483366] [1]Stop colling fail,ret -1
[  518.556321] cmd queue[1] crashed
[  518.559592] set max idx to LMAC failed!
[  518.563430] [1]Stop colling fail,ret -1
[  520.169865] cmd queue[1] crashed
[  520.173142] siwifi_hw->dbgdump_elem.err_cur_idx 5,5,86d60080,0,10
[  526.180790] cmd queue[1] crashed
[  532.186746] cmd queue[1] crashed
[  538.191609] cmd queue[1] crashed
[  544.196636] cmd queue[1] crashed
[  550.201578] cmd queue[1] crashed
[  556.206388] cmd queue[1] crashed
[  562.211472] cmd queue[1] crashed
[  568.216246] cmd queue[1] crashed
[  571.356069] cmd queue[1] crashed
[  571.359351] lmac_dump_registers band=1
[  571.363104] umac task_dump_registers-baseaddr=0xa2000000
[  571.368522] 
[  571.368522] $ 0:	ffffffff	ffffffff	ffffffff	ffffffff	
[  571.368522] $ 4:	ffffffff	ffffffff	ffffffff	ffffffff	
[  571.368522] $ 8:	ffffffff	ffffffff	ffffffff	ffffffff	
[  571.368522] $12:	ffffffff	ffffffff	ffffffff	ffffffff	
[  571.368522] $16:	ffffffff	ffffffff	ffffffff	ffffffff	
[  571.368522] $20:	ffffffff	ffffffff	ffffffff	ffffffff	
[  571.368522] $24:	ffffffff	ffffffff	
[  571.368522] $28:	ffffffff	ffffffff	ffffffff	ffffffff	
[  571.368735] epc: ffffffff
[  571.411800] ra: ffffffff
[  571.414370] Status: ffffffff
[  571.417367] Cause: ffffffff
[  571.420174] BadVA: ffffffff
[  571.422994] Prid: ffffffff
[  571.425724] Call Trace:
[  571.428325] [<0xffffffff>] <-
[  571.431328] [<0xffffffff>] <-
[  571.434306] [<0xffffffff>] <-
[  571.437391] [<0xffffffff>] <-
[  571.440378] [<0xffffffff>] <-
[  571.443345] [<0xffffffff>] <-
[  571.446411] [<0xffffffff>] <-
[  571.449420] [<0xffffffff>] <-
[  571.452418] [<0xffffffff>] <-
[  571.455393] [<0xffffffff>] <-
[  571.458493] [<0xffffffff>] <-
[  571.461472] [<0xffffffff>] <-
[  571.464468] [<0xffffffff>] <-
[  571.467570] [<0xffffffff>] <-
[  571.470561] [<0xffffffff>] <-
[  571.473552] [<0xffffffff>] <-
[  571.476726] [<0xffffffff>] <-
[  571.479723] [<0xffffffff>] <-
[  571.482690] [<0xffffffff>] <-
[  571.485654] [<0xffffffff>] <-
[  571.488739] [<0xffffffff>] <-
[  571.491722] [<0xffffffff>] <-
[  571.494689] [<0xffffffff>] <-
[  571.497748] [<0xffffffff>] <-
[  571.500727] [<0xffffffff>] <-
[  571.503694] [<0xffffffff>] <-
[  571.506729] [<0xffffffff>] <-

**Comment by Siflower** [comment]
Looks like not prepare hardware cause wifi dumb
